services:
  mongodb:
    profiles:
      - dev
      - prod
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tmp
      - MONGO_INITDB_ROOT_PASSWORD=tmp
    volumes:
      - './backend/database/data:/data/db'
    command: --quiet
    ports:
      - 27017:27017
  backend-dev:
    profiles:
      - dev
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=DEBUG
    volumes:
      - './backend/flaskr:/app/flaskr'
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
  backend:
    profiles:
      - prod
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=INFO
  frontend-dev:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules/
      - ./frontend/:/app/
    develop:
      watch:
        - action: rebuild
          path: package.json
  frontend:
    profiles:
      - prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
  nginx-dev:
    profiles:
      - dev
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  nginx:
    profiles:
      - prod
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "80:80"
