services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tmp
      - MONGO_INITDB_ROOT_PASSWORD=tmp
    ports:
      - 27017:27017
    volumes:
      - './cu2m-backend/database/data:/data/db'
    command: --quiet
  cu2m-backend:
    build:
      context: ./cu2m-backend/
    environment:
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
    develop:
      watch:
        - action: sync+restart
          path: ./cu2m-backend/flaskr
          target: /app/flaskr
          ignore:
            - __pycache__/
        - action: rebuild
          path: requirements.txt
  cu2m-frontend:
    build:
      context: ./cu2m-frontend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

