services:
  mongodb:
    profiles:
      - dev
      - prod
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tmp
      - MONGO_INITDB_ROOT_PASSWORD=tmp
    volumes:
      - './cu2m-backend/database/data:/data/db'
    command: --quiet
  cu2m-backend-dev:
    profiles:
      - dev
    build:
      context: ./cu2m-backend/
      dockerfile: Dockerfile
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=DEBUG
    volumes:
      - './cu2m-backend/flaskr:/app/flaskr'
    develop:
      watch:
        - action: rebuild
          path: pyproject.toml
  cu2m-backend:
    profiles:
      - prod
    build:
      context: ./cu2m-backend/
      dockerfile: Dockerfile.prod
    environment:
      - COURSE_DATA_FILENAME=courses.json
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - LOGGING_LEVEL=INFO
  cu2m-frontend-dev:
    profiles:
      - dev
    build:
      context: ./cu2m-frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules/
      - ./cu2m-frontend/:/app/
  cu2m-frontend:
    profiles:
      - prod
    build:
      context: ./cu2m-frontend
      dockerfile: Dockerfile.prod
  nginx-dev:
    profiles:
      - dev
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  nginx:
    profiles:
      - prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
